Bepro 1625 big token names breakes frontend layout
layerx-labs/webnetwork pull request #52
Opened 2023-05-24 19:01 UTC by MarcusviniciusLsantos

2023-05-25 14:57 UTC, moshmage requested changes

2023-05-26 13:37 UTC, moshmage commented on .github/PULL_REQUEST_TEMPLATE.md
> +# Pull Request Document
rebase your branch as this change is not from this PR

2023-05-26 13:41 UTC, moshmage commented on components/custom-network/network-contract-settings.tsx
> +        symbol: networkTokenSymbol?.length > 6 ? `${networkTokenSymbol.slice(0, 6)}...` : networkTokenSymbol
set this lenght (6) as a constant

2023-05-26 13:43 UTC, moshmage commented on components/profile/my-network-settings/governance-settings.tsx
> +  const networkTokenSymbol = symbol?.length > 12 ? `${symbol.slice(0, 12)}...` : symbol
set this value (12) as a constant (...SMALL ....LARGE)

2023-05-26 13:45 UTC, moshmage commented on components/token-symbol.tsx
> +import { CSSProperties } from "react";
this component can be moved to "common input components" like folder

2023-05-26 13:45 UTC, moshmage requested changes
add the min with values to constants so we can easily change them

2023-06-01 11:57 UTC, moshmage approved these changes

2023-06-02 22:28 UTC, vhcsilva approved these changes

2023-06-02 22:29 UTC, vhcsilva approved these changes

2023-06-02 22:30 UTC, merged