Bepro 1644 mobile wallet page
layerx-labs/webnetwork pull request #95
Opened 2023-07-03 20:02 UTC by MarcusviniciusLsantos

2023-07-12 10:15 UTC, moshmage requested changes

2023-07-12 10:15 UTC, moshmage commented on components/profile/pages/wallet/wallet-balance/controller.tsx
> +    getTokens(state?.connectedChain?.id).then((tokens) => {
if this depends on another state, we should remove this from this useEffect to avoid it running when we don't need it

2023-07-12 10:15 UTC, moshmage commented on components/profile/pages/wallet/wallet-balance/controller.tsx
> +    Promise.all(tokens.map(async (token) => ({
align with @vhcsilva to come to a solution about merging this functionality into one x-hook because this is repeated on both PRs

2023-07-12 10:15 UTC, moshmage commented on components/profile/pages/wallet/wallet-balance/controller.tsx
> +    if(!query?.networkName && query?.network){
shouldn't we just _not_ come to this page with `query.network` and instead have `query.networkName` be the default?

2023-07-14 08:09 UTC, moshmage approved these changes

2023-07-17 13:17 UTC, moshmage approved these changes

2023-07-19 12:43 UTC, vhcsilva requested changes

2023-07-19 12:43 UTC, vhcsilva commented on components/issue-filters/mobile-filters-modal.tsx
> +  function RenderFilterStructure({ label, children }: {label: string, children: ReactElement}) {
I'd recommend you to move this function to another file and make it a real component, as we have seen that type of component inside a component can lead to re-rendering issues

2023-07-19 12:43 UTC, vhcsilva commented on components/issue-filters/mobile-filters-modal.tsx
> +  function FilterComponent(label, options, type) {
Same for this function, make it a real component

2023-07-19 19:43 UTC, vhcsilva requested changes

2023-07-19 19:43 UTC, vhcsilva commented on components/issue-filters/mobile-filters-modal.tsx
> +          label="Repository"
Missing translations

2023-07-19 19:43 UTC, vhcsilva commented on components/issue-filters/mobile-filters-modal.tsx
> +          label="Bounty State"
Missing translations

2023-07-19 19:43 UTC, vhcsilva commented on components/issue-filters/mobile-filters-modal.tsx
> +          label="Timeframe"
Missing translations

2023-07-19 23:43 UTC, vhcsilva approved these changes

2023-07-21 14:07 UTC, merged